[project]
name = "llm-commit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click>=8.1.8",
    "prompt-toolkit>=3.0.48",
]

[project.entry-points."llm.plugins"]
commit = "llm_commit.plugin"
