[project]
name = "llm-commit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[project.entry-points."llm.plugins"]
myplugin = "llm_myplugin.plugin"
